# Generated by Django 5.2.5 on 2025-08-13 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_taxa_matricula', models.DecimalField(decimal_places=2, default=150.0, help_text='Valor da taxa de matrícula única para novos alunos.', max_digits=7)),
            ],
            options={
                'verbose_name': 'Configuração da Escola',
                'verbose_name_plural': 'Configurações da Escola',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('pagou_taxa_matricula', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario', models.TimeField()),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('capacidade', models.PositiveIntegerField(default=1)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.instrumento')),
            ],
            options={
                'verbose_name': 'Horário Fixo para Matrícula',
                'verbose_name_plural': 'Horários Fixos para Matrícula',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('status_pagamento_mes_atual', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.cliente')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.horariodisponivel')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.professor'),
        ),
        migrations.CreateModel(
            name='VagaAulaExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(unique=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('AGENDADA', 'Agendada')], default='DISPONIVEL', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=150.0, max_digits=7)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.cliente')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.instrumento')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.professor')),
            ],
            options={
                'verbose_name': 'Vaga para Aula Experimental',
                'verbose_name_plural': 'Vagas para Aulas Experimentais',
            },
        ),
    ]
