# Generated by Django 5.2.5 on 2025-08-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('IN', 'Iniciante'), ('IT', 'Intermediário'), ('AV', 'Avançado'), ('UN', 'Nível Único')], default='UN', max_length=2)),
                ('duracao_min', models.IntegerField(default=50, help_text='Duração da aula em minutos')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_experimental', models.BooleanField(default=False, help_text='Marque se for uma aula experimental.')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(help_text='Use o formato (XX) XXXXX-XXXX', max_length=15, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Violão, Piano, Canto', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instrumento_principal', models.CharField(max_length=50)),
                ('bio_curta', models.TextField(blank=True, help_text='Um breve resumo sobre o professor.')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('AG', 'Agendado'), ('CA', 'Cancelado'), ('RE', 'Realizado')], default='AG', max_length=2)),
                ('pagamento_status', models.CharField(choices=[('PE', 'Pendente'), ('AP', 'Aprovado'), ('RE', 'Recusado')], default='PE', max_length=2)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.aula')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamento.instrumento'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.professor'),
        ),
    ]
