# Generated by Django 5.2.5 on 2025-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='realizou_aula_experimental',
            field=models.BooleanField(default=False),
        ),
    ]
